wandb_version: 1

dataset_names:
  desc: null
  value:
  - boss_toxicity
icl_methods:
  desc: null
  value:
  - static
task_model_names:
  desc: null
  value:
  - trained_models/final_boss_toxicity/boss_toxicity/final
style_model_names:
  desc: null
  value:
  - TheBloke/vicuna-13B-1.1-HF
max_examples:
  desc: null
  value: 50
baslines:
  desc: null
  value:
  - fine-tuning
  - test_time_augmentation
  - memo
adaptive_methods:
  desc: null
  value:
  - No Adaptation
  - fine-tuning
  - test_time_augmentation
  - memo
  - TheBloke/vicuna-13B-1.1-HF
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.28.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687061708.113568
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 95
      - 100
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 95
      - 100
      3:
      - 13
      - 16
      - 23
      4: 3.10.11
      5: 0.15.4
      6: 4.28.1
      8:
      - 5
